// Generated by scripts/generate-design-tokens.py. Edit design/tokens.json.
pub mod palette {
    pub const NAVY_700: lucent_api::Color = lucent_api::Color::hex(0x2c5184);
    pub const NAVY_950: lucent_api::Color = lucent_api::Color::hex(0x17334b);
    pub const CYAN_200: lucent_api::Color = lucent_api::Color::hex(0xbce8f4);
    pub const CYAN_300: lucent_api::Color = lucent_api::Color::hex(0x73dcee);
    pub const CYAN_700: lucent_api::Color = lucent_api::Color::hex(0x1b6a7d);
    pub const CYAN_800: lucent_api::Color = lucent_api::Color::hex(0x176075);
    pub const SKY_200: lucent_api::Color = lucent_api::Color::hex(0xbadbea);
    pub const AQUA_100: lucent_api::Color = lucent_api::Color::hex(0xb1e9eb);
    pub const AQUA_950: lucent_api::Color = lucent_api::Color::hex(0x153f5b);
    pub const CORAL_200: lucent_api::Color = lucent_api::Color::hex(0xffcfbc);
    pub const CORAL_800: lucent_api::Color = lucent_api::Color::hex(0x9c2e16);
    pub const GREEN_300: lucent_api::Color = lucent_api::Color::hex(0xa7ead3);
    pub const GREEN_800: lucent_api::Color = lucent_api::Color::hex(0x236144);
    pub const AMBER_200: lucent_api::Color = lucent_api::Color::hex(0xf4d48f);
    pub const AMBER_800: lucent_api::Color = lucent_api::Color::hex(0x754e08);
    pub const INK_950: lucent_api::Color = lucent_api::Color::hex(0x10191c);
    pub const INK_900: lucent_api::Color = lucent_api::Color::hex(0x172327);
    pub const INK_850: lucent_api::Color = lucent_api::Color::hex(0x1c2b2e);
    pub const INK_800: lucent_api::Color = lucent_api::Color::hex(0x243b34);
    pub const INK_700: lucent_api::Color = lucent_api::Color::hex(0x314044);
    pub const INK_600: lucent_api::Color = lucent_api::Color::hex(0x486958);
    pub const SAGE_300: lucent_api::Color = lucent_api::Color::hex(0xa6b8b8);
    pub const SAGE_100: lucent_api::Color = lucent_api::Color::hex(0xf1f2e9);
    pub const MINT_100: lucent_api::Color = lucent_api::Color::hex(0xd4f3cf);
    pub const BLACK: lucent_api::Color = lucent_api::Color::hex(0x000000);
    pub const WHITE: lucent_api::Color = lucent_api::Color::hex(0xffffff);
}
pub mod space {
    pub const HAIRLINE: f32 = 1.0;
    pub const XXS: f32 = 2.0;
    pub const XS: f32 = 4.0;
    pub const SM: f32 = 8.0;
    pub const MD: f32 = 12.0;
    pub const LG: f32 = 16.0;
    pub const XL: f32 = 20.0;
    pub const XXL: f32 = 24.0;
    pub const SECTION: f32 = 32.0;
    pub const WIDE: f32 = 40.0;
    pub const PAGE: f32 = 64.0;
}
pub mod radius {
    pub const INDICATOR: f32 = 2.0;
    pub const SMALL: f32 = 8.0;
    pub const CONTROL: f32 = 18.0;
    pub const BUTTON: f32 = 20.0;
    pub const CARD: f32 = 22.0;
    pub const SEARCH: f32 = 25.0;
    pub const PANEL: f32 = 20.0;
    pub const WIDGET: f32 = 30.0;
}
pub mod font {
    pub const MICRO: f32 = 10.0;
    pub const CAPTION: f32 = 11.0;
    pub const SMALL: f32 = 12.0;
    pub const CONTROL: f32 = 13.0;
    pub const BODY: f32 = 14.0;
    pub const LABEL: f32 = 15.0;
    pub const HEADING: f32 = 17.0;
    pub const TITLE: f32 = 23.0;
    pub const TEMPERATURE: f32 = 32.0;
    pub const TIMER: f32 = 51.0;
    pub const CLOCK: f32 = 110.0;
}
pub mod opacity {
    pub const SUBTLE: f32 = 0.08;
    pub const HOVER: f32 = 0.16;
    pub const SHADOW: f32 = 0.22;
    pub const DISABLED: f32 = 0.3;
    pub const QUIET: f32 = 0.4;
    pub const SECONDARY: f32 = 0.65;
    pub const MUTED: f32 = 0.75;
    pub const SUPPORTING: f32 = 0.8;
    pub const STRONG: f32 = 0.9;
}
pub mod motion {
    pub const PANEL: f64 = 0.5;
    pub const ENTER: f64 = 0.32;
    pub const EXIT: f64 = 0.19;
    pub const SELECTION: f64 = 0.35;
    pub const HOVER: f64 = 0.16;
    pub const SPATIAL: [f32; 4] = [0.38, 1.21, 0.22, 1.0];
    pub const DECELERATE: [f32; 4] = [0.05, 0.7, 0.1, 1.0];
}
pub mod theme {
    pub mod dark {
        pub const SURFACE: lucent_api::Color = lucent_api::Color::hex(0x2c5184);
        pub const SURFACE_CONTAINER: lucent_api::Color = lucent_api::Color::hex(0x1b6a7d);
        pub const ON_SURFACE: lucent_api::Color = lucent_api::Color::hex(0xbce8f4);
        pub const PRIMARY: lucent_api::Color = lucent_api::Color::hex(0x73dcee);
        pub const ON_PRIMARY: lucent_api::Color = lucent_api::Color::hex(0x153f5b);
        pub const ERROR: lucent_api::Color = lucent_api::Color::hex(0xffcfbc);
        pub const SUCCESS: lucent_api::Color = lucent_api::Color::hex(0xa7ead3);
        pub const WARNING: lucent_api::Color = lucent_api::Color::hex(0xf4d48f);
        pub const INFO: lucent_api::Color = lucent_api::Color::hex(0xbce8f4);
        pub const FOCUS: lucent_api::Color = lucent_api::Color::hex(0x73dcee);
    }
    pub mod light {
        pub const SURFACE: lucent_api::Color = lucent_api::Color::hex(0xbadbea);
        pub const SURFACE_CONTAINER: lucent_api::Color = lucent_api::Color::hex(0xb1e9eb);
        pub const ON_SURFACE: lucent_api::Color = lucent_api::Color::hex(0x17334b);
        pub const PRIMARY: lucent_api::Color = lucent_api::Color::hex(0x176075);
        pub const ON_PRIMARY: lucent_api::Color = lucent_api::Color::hex(0xffffff);
        pub const ERROR: lucent_api::Color = lucent_api::Color::hex(0x9c2e16);
        pub const SUCCESS: lucent_api::Color = lucent_api::Color::hex(0x236144);
        pub const WARNING: lucent_api::Color = lucent_api::Color::hex(0x754e08);
        pub const INFO: lucent_api::Color = lucent_api::Color::hex(0x176075);
        pub const FOCUS: lucent_api::Color = lucent_api::Color::hex(0x176075);
    }
}
pub mod web {
    pub const BACKGROUND: lucent_api::Color = lucent_api::Color::hex(0x10191c);
    pub const SURFACE: lucent_api::Color = lucent_api::Color::hex(0x172327);
    pub const SURFACE_RAISED: lucent_api::Color = lucent_api::Color::hex(0x1c2b2e);
    pub const SURFACE_ACCENT: lucent_api::Color = lucent_api::Color::hex(0x243b34);
    pub const BORDER: lucent_api::Color = lucent_api::Color::hex(0x314044);
    pub const BORDER_STRONG: lucent_api::Color = lucent_api::Color::hex(0x486958);
    pub const TEXT: lucent_api::Color = lucent_api::Color::hex(0xf1f2e9);
    pub const MUTED: lucent_api::Color = lucent_api::Color::hex(0xa6b8b8);
    pub const PRIMARY: lucent_api::Color = lucent_api::Color::hex(0xa7ead3);
    pub const ON_PRIMARY: lucent_api::Color = lucent_api::Color::hex(0x10191c);
    pub const FEATURE: lucent_api::Color = lucent_api::Color::hex(0xd4f3cf);
    pub const ON_FEATURE: lucent_api::Color = lucent_api::Color::hex(0x243b34);
    pub const INFO: lucent_api::Color = lucent_api::Color::hex(0xbce8f4);
    pub const WARM: lucent_api::Color = lucent_api::Color::hex(0xffcfbc);
}
pub mod component {
    pub mod button {
        pub const RADIUS: f32 = 20.0;
        pub const PADDING_INLINE: f32 = 20.0;
        pub const PADDING_BLOCK: f32 = 8.0;
    }
    pub mod wallpaper {
        pub const ASPECT_RATIO: f32 = 0.62;
        pub const VISIBLE_DISTANCE: f32 = 3.2;
        pub const PREVIOUS_LEFT: f32 = 5.0;
        pub const CAPTION_GAP: f32 = 6.0;
        pub const CAPTION_INSET: f32 = 10.0;
        pub const CAPTION_INSETS: f32 = 20.0;
        pub const CAPTION_HEIGHT: f32 = 30.0;
        pub const BUTTON_HEIGHT: f32 = 36.0;
        pub const NEXT_INSET: f32 = 38.0;
        pub const FOOTER_HEIGHT: f32 = 40.0;
        pub const FAR_SHRINK: f32 = 88.0;
        pub const NEAR_SHRINK: f32 = 102.0;
        pub const BUTTON_WIDTH: f32 = 180.0;
        pub const FAR_STEP: f32 = 205.0;
        pub const STAGE_HEIGHT: f32 = 230.0;
        pub const NEAR_STEP: f32 = 300.0;
        pub const HERO_WIDTH: f32 = 340.0;
    }
    pub mod launcher {
        pub const THEME_HALF_GAP: f32 = 5.0;
        pub const ERROR_HEIGHT: f32 = 24.0;
        pub const ICON_WIDTH: f32 = 28.0;
        pub const TAB_HEIGHT: f32 = 32.0;
        pub const HEADER_HEIGHT: f32 = 32.0;
        pub const RESET_HEIGHT: f32 = 36.0;
        pub const RESET_BOTTOM: f32 = 38.0;
        pub const BODY_TOP: f32 = 44.0;
        pub const ROW_HEIGHT: f32 = 46.0;
        pub const COMMAND_HEIGHT: f32 = 46.0;
        pub const WIDGET_ROW_HEIGHT: f32 = 49.0;
        pub const BODY_MIN_HEIGHT: f32 = 50.0;
        pub const EMPTY_HEIGHT: f32 = 70.0;
        pub const ERROR_BOTTOM: f32 = 71.0;
        pub const THEME_HEIGHT: f32 = 84.0;
        pub const THEME_CAPTION_TOP: f32 = 100.0;
        pub const ROW_PADDING_INLINE: f32 = 16.0;
        pub const ROW_PADDING_BLOCK: f32 = 8.0;
    }
    pub mod dock_row {
        pub const INDICATOR_HEIGHT: f32 = 2.0;
        pub const INDICATOR_WIDTH: f32 = 11.0;
        pub const INDICATOR_LEFT: f32 = 15.0;
        pub const INDICATOR_TOP: f32 = 36.0;
        pub const ITEM_SIZE: f32 = 41.0;
        pub const HEIGHT: f32 = 42.0;
    }
    pub mod dock {
        pub const ROW_TOP: f32 = 8.0;
        pub const ROW_LEFT: f32 = 16.0;
        pub const BOTTOM: f32 = 12.0;
        pub const CONTENT_INSET: f32 = 20.0;
        pub const MINIMUM_HEIGHT: f32 = 40.0;
        pub const MINIMUM_WIDTH: f32 = 60.0;
    }
    pub mod bar {
        pub const RING_INSET: f32 = 3.5;
        pub const DOT_SIZE: f32 = 5.0;
        pub const DOT_INSET: f32 = 9.5;
        pub const TOP: f32 = 12.0;
        pub const LEFT: f32 = 16.0;
        pub const RING_SIZE: f32 = 17.0;
        pub const WORKSPACE_SIZE: f32 = 24.0;
        pub const TIME_WIDTH: f32 = 50.0;
        pub const DATE_WIDTH: f32 = 78.0;
        pub const SYSTEM_WIDTH: f32 = 148.0;
        pub const MEDIA_TEXT_WIDTH: f32 = 135.0;
        pub const CLOCK_WIDTH: f32 = 218.0;
    }
    pub mod pill {
        pub const HEIGHT: f32 = 32.0;
        pub const PADDING_INLINE: f32 = 12.0;
        pub const PADDING_BLOCK: f32 = 4.0;
    }
    pub mod icon_button {
        pub const EXTENT: f32 = 33.0;
        pub const PADDING: f32 = 7.0;
    }
    pub mod timer {
        pub const HEADING_TOP: f32 = 13.0;
        pub const INSET: f32 = 20.0;
        pub const HEADING_HEIGHT: f32 = 28.0;
        pub const BUTTON_HEIGHT: f32 = 37.0;
        pub const TIME_TOP: f32 = 47.0;
        pub const TIME_HEIGHT: f32 = 70.0;
        pub const RESET_WIDTH: f32 = 78.0;
        pub const BUTTONS_TOP: f32 = 135.0;
        pub const TOGGLE_WIDTH: f32 = 142.0;
        pub const RESET_LEFT: f32 = 172.0;
        pub const CONTENT_WIDTH: f32 = 230.0;
    }
    pub mod notes {
        pub const HEADING_TOP: f32 = 15.0;
        pub const CAPTION_HEIGHT: f32 = 18.0;
        pub const INSET: f32 = 20.0;
        pub const HEADING_HEIGHT: f32 = 30.0;
        pub const INPUT_TOP: f32 = 55.0;
        pub const INPUT_HEIGHT: f32 = 60.0;
        pub const CAPTION_TOP: f32 = 128.0;
        pub const CONTENT_WIDTH: f32 = 230.0;
    }
    pub mod system {
        pub const PROGRESS_HEIGHT: f32 = 4.0;
        pub const HEADING_TOP: f32 = 14.0;
        pub const INSET: f32 = 18.0;
        pub const NETWORK_HEIGHT: f32 = 23.0;
        pub const LABEL_HEIGHT: f32 = 24.0;
        pub const HEADING_HEIGHT: f32 = 28.0;
        pub const CPU_TOP: f32 = 53.0;
        pub const CPU_PROGRESS_TOP: f32 = 84.0;
        pub const MEMORY_TOP: f32 = 98.0;
        pub const MEMORY_PROGRESS_TOP: f32 = 129.0;
        pub const NETWORK_TOP: f32 = 144.0;
        pub const CONTENT_WIDTH: f32 = 234.0;
    }
    pub mod media {
        pub const PROGRESS_HEIGHT: f32 = 3.0;
        pub const INSET: f32 = 18.0;
        pub const ARTIST_HEIGHT: f32 = 24.0;
        pub const TITLE_HEIGHT: f32 = 28.0;
        pub const PLAY_HEIGHT: f32 = 44.0;
        pub const PREVIOUS_LEFT: f32 = 58.0;
        pub const PLAY_WIDTH: f32 = 60.0;
        pub const FALLBACK_TOP: f32 = 67.0;
        pub const FALLBACK_LEFT: f32 = 77.0;
        pub const PLAY_LEFT: f32 = 100.0;
        pub const NEXT_LEFT: f32 = 168.0;
        pub const ARTWORK_HEIGHT: f32 = 213.0;
        pub const CONTENT_WIDTH: f32 = 224.0;
        pub const TITLE_TOP: f32 = 241.0;
        pub const ARTIST_TOP: f32 = 271.0;
        pub const PROGRESS_TOP: f32 = 310.0;
        pub const PLAY_TOP: f32 = 330.0;
        pub const NAVIGATION_TOP: f32 = 337.0;
    }
    pub mod weather {
        pub const ICON_BACKGROUND_LEFT: f32 = 18.0;
        pub const ICON_BACKGROUND_TOP: f32 = 24.0;
        pub const ICON_LEFT: f32 = 28.0;
        pub const TEMPERATURE_TOP: f32 = 29.0;
        pub const DESCRIPTION_HEIGHT: f32 = 30.0;
        pub const ICON_TOP: f32 = 33.0;
        pub const TEMPERATURE_HEIGHT: f32 = 46.0;
        pub const DESCRIPTION_TOP: f32 = 72.0;
        pub const ICON_BACKGROUND_SIZE: f32 = 82.0;
        pub const TEXT_LEFT: f32 = 116.0;
        pub const TEMPERATURE_WIDTH: f32 = 134.0;
        pub const DESCRIPTION_WIDTH: f32 = 145.0;
    }
    pub mod calendar {
        pub const PETAL_TOP: f32 = 3.5;
        pub const PETAL_LEFT: f32 = 4.5;
        pub const PETAL_ORBIT: f32 = 5.0;
        pub const NAVIGATION_TOP: f32 = 15.0;
        pub const HEADING_TOP: f32 = 16.0;
        pub const WEEKDAY_LEFT: f32 = 18.0;
        pub const LEFT: f32 = 19.0;
        pub const PETAL_SIZE: f32 = 22.0;
        pub const WEEKDAY_HEIGHT: f32 = 25.0;
        pub const DAY_HEIGHT: f32 = 29.0;
        pub const ROW_HEIGHT: f32 = 30.0;
        pub const DAY_WIDTH: f32 = 31.0;
        pub const COLUMN_WIDTH: f32 = 33.0;
        pub const WEEKDAY_TOP: f32 = 51.0;
        pub const DAYS_TOP: f32 = 79.0;
        pub const HEADING_WIDTH: f32 = 172.0;
        pub const PREVIOUS_LEFT: f32 = 189.0;
        pub const NEXT_LEFT: f32 = 224.0;
    }
    pub mod clock {
        pub const HOUR_TOP: f32 = 5.0;
        pub const DATE_HEIGHT: f32 = 24.0;
        pub const MINUTE_TOP: f32 = 104.0;
        pub const DIGIT_HEIGHT: f32 = 119.0;
        pub const DATE_TOP: f32 = 221.0;
        pub const WIDTH: f32 = 248.0;
    }
    pub mod widget_layout {
        pub const LEFT: f32 = 20.0;
        pub const WEATHER_LEFT: f32 = 25.0;
        pub const TOP: f32 = 110.0;
        pub const CLOCK_TOP: f32 = 215.0;
        pub const RIGHT_INSET: f32 = 280.0;
        pub const TIMER_TOP: f32 = 310.0;
        pub const SECOND_COLUMN: f32 = 320.0;
        pub const WEATHER_TOP: f32 = 400.0;
        pub const MEDIA_TOP: f32 = 495.0;
        pub const SYSTEM_TOP: f32 = 560.0;
        pub const GRID_STEP: f32 = 16.0;
    }
    pub mod widget_size {
        pub mod calendar {
            pub const WIDTH: f32 = 270.0;
            pub const HEIGHT: f32 = 276.0;
        }
        pub mod clock {
            pub const WIDTH: f32 = 248.0;
            pub const HEIGHT: f32 = 264.0;
        }
        pub mod weather {
            pub const WIDTH: f32 = 270.0;
            pub const HEIGHT: f32 = 130.0;
        }
        pub mod media {
            pub const WIDTH: f32 = 260.0;
            pub const HEIGHT: f32 = 392.0;
        }
        pub mod system {
            pub const WIDTH: f32 = 270.0;
            pub const HEIGHT: f32 = 180.0;
        }
        pub mod notes {
            pub const WIDTH: f32 = 270.0;
            pub const HEIGHT: f32 = 160.0;
        }
        pub mod timer {
            pub const WIDTH: f32 = 270.0;
            pub const HEIGHT: f32 = 190.0;
        }
        pub mod fallback {
            pub const WIDTH: f32 = 200.0;
            pub const HEIGHT: f32 = 150.0;
        }
    }
    pub mod panel {
        pub const INITIAL_WIDTH: f32 = 350.0;
        pub const DOCK_HEIGHT: f32 = 57.0;
        pub const WALLPAPER_WIDTH: f32 = 1248.0;
        pub const LAUNCHER_WIDTH: f32 = 448.0;
        pub const VIEWPORT_INSETS: f32 = 40.0;
        pub const WALLPAPER_HEIGHT: f32 = 380.0;
        pub const LAUNCHER_MIN_HEIGHT: f32 = 218.0;
        pub const LAUNCHER_MAX_HEIGHT: f32 = 500.0;
        pub const WIDGETS_HEIGHT: f32 = 506.0;
        pub const COMMANDS_HEIGHT: f32 = 440.0;
        pub const THEMES_HEIGHT: f32 = 272.0;
        pub const BAR_HEIGHT: f32 = 56.0;
    }
    pub mod focus {
        pub const WIDTH: f32 = 2.0;
    }
    pub mod input {
        pub const HEIGHT: f32 = 44.0;
        pub const CARET_WIDTH: f32 = 1.5;
        pub const PADDING_INLINE: f32 = 16.0;
        pub const PADDING_BLOCK: f32 = 8.0;
    }
    pub mod switch {
        pub const WIDTH: f32 = 32.0;
        pub const HEIGHT: f32 = 18.0;
        pub const THUMB: f32 = 14.0;
        pub const INSET: f32 = 2.0;
    }
    pub mod window {
        pub const RADIUS: f32 = 20.0;
    }
    pub mod notification {
        pub const WIDTH: f32 = 400.0;
        pub const MARGIN: f32 = 16.0;
        pub const PADDING: f32 = 16.0;
        pub const GAP: f32 = 8.0;
        pub const TITLE_LINES: f32 = 2.0;
        pub const BODY_LINES: f32 = 3.0;
        pub const TOAST_LIMIT: f32 = 3.0;
        pub const MAX_CARD_HEIGHT: f32 = 320.0;
    }
    pub mod authentication {
        pub const WIDTH: f32 = 480.0;
        pub const HEIGHT: f32 = 460.0;
        pub const PADDING: f32 = 20.0;
        pub const TITLE_SIZE: f32 = 17.0;
        pub const INPUT_SIZE: f32 = 23.0;
        pub const INPUT_HEIGHT: f32 = 56.0;
    }
}
pub mod icon {
    pub const TINY: f32 = 16.0;
    pub const SMALL: f32 = 17.0;
    pub const COMPACT: f32 = 18.0;
    pub const CONTROL: f32 = 19.0;
    pub const MEDIUM: f32 = 20.0;
    pub const ACTION: f32 = 22.0;
    pub const LAUNCHER: f32 = 23.0;
    pub const WIDGET: f32 = 24.0;
    pub const APP: f32 = 28.0;
    pub const WEATHER: f32 = 61.0;
    pub const ARTWORK: f32 = 70.0;
}
pub mod web_type {
    pub const MICRO: f32 = 8.0;
    pub const MICRO_LARGE: f32 = 9.0;
    pub const CAPTION_SMALL: f32 = 10.0;
    pub const CAPTION: f32 = 11.0;
    pub const CODE: f32 = 11.5;
    pub const SMALL: f32 = 12.0;
    pub const CONTROL: f32 = 13.0;
    pub const BODY: f32 = 14.0;
    pub const BODY_LARGE: f32 = 15.0;
    pub const LEAD_SMALL: f32 = 16.0;
    pub const LEAD: f32 = 17.0;
    pub const LEAD_LARGE: f32 = 18.0;
    pub const TITLE_SMALL: f32 = 19.0;
    pub const TITLE_MEDIUM: f32 = 20.0;
    pub const TITLE: f32 = 21.0;
    pub const TITLE_LARGE: f32 = 22.0;
    pub const HEADING_SMALL: f32 = 23.0;
    pub const HEADING_MEDIUM: f32 = 24.0;
    pub const HEADING: f32 = 25.0;
    pub const HEADING_LARGE: f32 = 26.0;
    pub const SECTION_SMALL: f32 = 28.0;
    pub const SECTION: f32 = 30.0;
    pub const SECTION_LARGE: f32 = 32.0;
    pub const DISPLAY_SMALL: f32 = 33.0;
    pub const DISPLAY: f32 = 34.0;
    pub const DISPLAY_LARGE: f32 = 35.0;
    pub const FEATURE_SMALL: f32 = 36.0;
    pub const FEATURE: f32 = 40.0;
    pub const FEATURE_LARGE: f32 = 42.0;
    pub const HERO_SMALL: f32 = 49.0;
    pub const HERO_LARGE: f32 = 58.0;
    pub const METRIC_SMALL: f32 = 62.0;
    pub const METRIC: f32 = 72.0;
    pub const METRIC_LARGE: f32 = 75.0;
    pub const MASTHEAD: f32 = 98.0;
}
pub mod web_space {
    pub const SECTION_COMPACT: f32 = 80.0;
    pub const SECTION_STANDARD: f32 = 100.0;
    pub const SECTION_LARGE: f32 = 116.0;
}
pub mod app_icon {
    pub const CANVAS: f32 = 48.0;
    pub const GLYPH_INSET: f32 = 9.0;
    pub const GLYPH_EXTENT: f32 = 30.0;
    pub const STROKE: f32 = 1.8;
}
