[package]
name = "lucent-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
lucent-wayland = { path = "../../crates/lucent-wayland" }
lucent-api = { path = "../../crates/lucent-api" }
lucent-domain = { path = "../../crates/lucent-domain" }
lucent-usecases = { path = "../../crates/lucent-usecases" }
lucent-services = { path = "../../crates/lucent-services" }
serde_json = "1"
lucent-design = { path = "../../crates/lucent-design" }
