[package]
name = "lucent-services"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
lucent-domain = { path = "../lucent-domain" }
lucent-api = { path = "../lucent-api" }
serde_json = "1"
libc = "0.2"
chrono = "0.4"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp"] }
resvg = "0.45"
zbus = "5.19"
lucent-usecases = { path = "../lucent-usecases" }
jpeg-decoder = { version = "0.3.2", default-features = false }
