general {
    hide_cursor = true
}
background {
    color = rgba(12171aff)
}
label {
    text = Desktop Lab
    color = rgba(bbe9ffff)
    font_size = 36
    position = 0, 120
    halign = center
    valign = center
}
input-field {
    size = 320, 60
    outline_thickness = 2
    dots_center = true
    outer_color = rgba(8ad0eeff)
    inner_color = rgba(202b31ff)
    font_color = rgba(e0f3ffff)
    placeholder_text = Password
    position = 0, 0
    halign = center
    valign = center
}
