#!/usr/bin/env python3
"""Generate Lucent app SVGs and the typed desktop-ID catalog from shared tokens."""
import argparse
import importlib.util
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('design_tokens', ROOT/'scripts/generate-design-tokens.py')
tokens = importlib.util.module_from_spec(spec)
spec.loader.exec_module(tokens)


def outputs():
    values = tokens.resolve(tokens.flatten(json.loads(tokens.SOURCE.read_text())))
    icons = json.loads((ROOT/'design/app-icons.json').read_text())['icons']
    base = ROOT/'lucent/crates/lucent-design'
    ids, aliases, files = set(), set(), {}
    code = ['// Generated by scripts/generate-app-icons.py. Edit design/app-icons.json and design/tokens.json.',
            '#[derive(Clone, Copy, Debug)]',
            "pub struct AppIcon { pub id: &'static str, pub name: &'static str, pub desktop_ids: &'static [&'static str], pub svg: &'static str }",
            'pub const ALL: &[AppIcon] = &[']
    v=lambda key: values['app_icon.'+key]
    edge=v('canvas')
    for icon in icons:
        name = icon['id']
        if not re.fullmatch('[a-z][a-z0-9-]*',name) or name in ids: raise ValueError('Duplicate/invalid icon ID: '+name)
        ids.add(name)
        for alias in icon['desktop_ids']:
            if not alias.endswith('.desktop') or alias.casefold() in aliases: raise ValueError('Duplicate/invalid desktop ID: '+alias)
            aliases.add(alias.casefold())
        glyph=icon['glyph']
        for node in ET.fromstring('<g>'+glyph+'</g>').iter():
            if node.tag not in {'g','path','rect','circle','ellipse','line','polyline','polygon'}: raise ValueError('Only native vector geometry is allowed')
            if any(k not in {'d','x','y','width','height','rx','ry','cx','cy','r','x1','x2','y1','y2','points'} for k in node.attrib): raise ValueError('Unexpected vector attribute')
        # White alpha artwork is tinted by the native semantic foreground at paint time.
        ink=values['palette.white']
        svg=f'''<!-- Generated Lucent artwork. MIT. Source: design/app-icons.json -->
<svg xmlns="http://www.w3.org/2000/svg" width="{edge}" height="{edge}" viewBox="0 0 {edge} {edge}">
<g transform="translate({v('glyph_inset')} {v('glyph_inset')}) scale({v('glyph_extent')/24})" fill="none" stroke="{ink}" stroke-width="{v('stroke')}" stroke-linecap="round" stroke-linejoin="round">{glyph}</g></svg>
'''
        files[base/'assets/apps'/f'{name}.svg']=svg
        code += ['AppIcon { id: '+json.dumps(name)+', name: '+json.dumps(icon['name'])+', desktop_ids: &'+json.dumps(icon['desktop_ids'])+', svg: include_str!("../assets/apps/'+name+'.svg") },']
    code += ['];','pub const FALLBACK: &AppIcon = &ALL[0];', "pub fn lookup(desktop_id: &str) -> Option<&'static AppIcon> { ALL.iter().find(|icon| icon.desktop_ids.iter().any(|id| id.eq_ignore_ascii_case(desktop_id))) }", '']
    files[base/'src/app_icons.rs']='\n'.join(code)
    return files


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    files=outputs();stale=[]
    for path,content in files.items():
        if args.check:
            if not path.exists() or path.read_text()!=content:stale.append(str(path.relative_to(ROOT)))
        else:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content)
    if stale:raise SystemExit('Run python3 scripts/generate-app-icons.py; stale: '+', '.join(stale))
    print(f'{len(files)-1} app icons '+('verified' if args.check else 'generated'))

if __name__=='__main__':main()
