#!/usr/bin/env python3
"""Compile the shared, reference-based design tokens to Rust and CSS. No dependencies."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'design/tokens.json'


def flatten(tree, prefix=''):
    result = {}
    for key, value in tree.items():
        if key.startswith('$'):
            continue
        if not re.fullmatch(r'[a-z][a-z0-9_]*', key):
            raise ValueError(f'Invalid token name: {key}')
        path = f'{prefix}.{key}' if prefix else key
        if '$value' in value:
            result[path] = value
        else:
            result.update(flatten(value, path))
    return result


def resolve(tokens):
    values = {}
    def visit(name, chain=()):
        if name in chain:
            raise ValueError(f'Cyclic token: {name}')
        if name not in tokens:
            raise ValueError(f'Unknown token: {name}')
        if name in values:
            return values[name]
        token = tokens[name]
        kind, value = token['$type'], token['$value']
        if isinstance(value, str) and value.startswith('{') and value.endswith('}'):
            target = value[1:-1]
            value = visit(target, (*chain, name))
            if kind != tokens[target]['$type']:
                raise ValueError(f'Type mismatch: {name} → {target}')
        valid = ((kind == 'color' and isinstance(value, str) and re.fullmatch(r'#[0-9a-f]{6}', value))
                 or (kind in ('dimension', 'number', 'duration') and isinstance(value, (int, float))
                     and not isinstance(value, bool) and value >= 0)
                 or (kind == 'bezier' and isinstance(value, list) and len(value) == 4
                     and all(isinstance(v, (int, float)) for v in value)
                     and 0 <= value[0] <= 1 and 0 <= value[2] <= 1))
        if not valid:
            raise ValueError(f'Invalid {kind} token: {name}')
        values[name] = value
        return value
    for name in tokens:
        visit(name)
    return values


def css_value(kind, value):
    if kind == 'dimension': return f'{value:g}px'
    if kind == 'duration': return f'{value:g}ms'
    if kind == 'bezier': return 'cubic-bezier(' + ', '.join(f'{v:g}' for v in value) + ')'
    return str(value)


def outputs(tree):
    tokens = flatten(tree)
    values = resolve(tokens)
    def rust(group, prefix='', depth=0):
        lines = []
        for key, token in group.items():
            if key.startswith('$'): continue
            path = f'{prefix}.{key}' if prefix else key
            indent = '    ' * depth
            if '$value' not in token:
                lines += [f'{indent}pub mod {key} {{', *rust(token, path, depth + 1), f'{indent}}}']
                continue
            kind, value = token['$type'], values[path]
            if kind == 'color': ty, literal = 'lucent_api::Color', f'lucent_api::Color::hex(0x{value[1:]})'
            elif kind == 'bezier': ty, literal = '[f32; 4]', '[' + ', '.join(str(float(v)) for v in value) + ']'
            elif kind == 'duration': ty, literal = 'f64', str(float(value) / 1000)
            else: ty, literal = 'f32', str(float(value))
            lines.append(f'{indent}pub const {key.upper()}: {ty} = {literal};')
        return lines
    rust_text = '// Generated by scripts/generate-design-tokens.py. Edit design/tokens.json.\n' + '\n'.join(rust(tree)) + '\n'
    css = ['/* Generated by scripts/generate-design-tokens.py. Edit design/tokens.json. */', ':root {']
    for name, token in tokens.items():
        raw = token['$value']
        value = f'var(--{raw[1:-1].replace(".", "-").replace("_", "-")})' if isinstance(raw, str) and raw.startswith('{') else css_value(token['$type'], values[name])
        css.append(f'  --{name.replace(".", "-").replace("_", "-").replace("_", "-")}: {value};')
    css.append('}')
    return {
        ROOT / 'lucent/crates/lucent-design/src/tokens.rs': rust_text,
        ROOT / 'site/src/styles/tokens.css': '\n'.join(css) + '\n',
        ROOT / 'configs/lucent/window-rules.lua': (
            '-- Generated from component.window.radius in design/tokens.json.\n'
            '-- Compositor default; explicit app rules and Omarchy gap toggles retain precedence.\n'
            'hl.config({\n'
            f'  decoration = {{ rounding = {values["component.window.radius"]:g} }},\n'
            '})\n'
        ),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if generated tokens are stale')
    args = parser.parse_args()
    tree = json.loads(SOURCE.read_text())
    stale = []
    for path, content in outputs(tree).items():
        if args.check:
            if not path.exists() or path.read_text() != content: stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        raise SystemExit('Run python3 scripts/generate-design-tokens.py; stale: ' + ', '.join(stale))
    print(f'{len(flatten(tree))} design tokens verified' if args.check else 'Generated Rust and CSS design tokens')


if __name__ == '__main__': main()
