#!/usr/bin/env python3
"""Compile the shared, reference-based design tokens to Rust and CSS. No dependencies."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'design/tokens.json'


def flatten(tree, prefix=''):
    result = {}
    for key, value in tree.items():
        if key.startswith('$'):
            continue
        if not re.fullmatch(r'[a-z][a-z0-9_]*', key):
            raise ValueError(f'Invalid token name: {key}')
        path = f'{prefix}.{key}' if prefix else key
        if '$value' in value:
            result[path] = value
        else:
            result.update(flatten(value, path))
    return result


def resolve(tokens):
    values = {}
    def visit(name, chain=()):
        if name in chain:
            raise ValueError(f'Cyclic token: {name}')
        if name not in tokens:
            raise ValueError(f'Unknown token: {name}')
        if name in values:
            return values[name]
        token = tokens[name]
        kind, value = token['$type'], token['$value']
        if isinstance(value, str) and value.startswith('{') and value.endswith('}'):
            target = value[1:-1]
            value = visit(target, (*chain, name))
            if kind != tokens[target]['$type']:
                raise ValueError(f'Type mismatch: {name} → {target}')
        valid = ((kind == 'color' and isinstance(value, str) and re.fullmatch(r'#[0-9a-f]{6}', value))
                 or (kind in ('dimension', 'number', 'duration') and isinstance(value, (int, float))
                     and not isinstance(value, bool) and value >= 0)
                 or (kind == 'bezier' and isinstance(value, list) and len(value) == 4
                     and all(isinstance(v, (int, float)) for v in value)
                     and 0 <= value[0] <= 1 and 0 <= value[2] <= 1))
        if not valid:
            raise ValueError(f'Invalid {kind} token: {name}')
        values[name] = value
        return value
    for name in tokens:
        visit(name)
    return values


def css_value(kind, value):
    if kind == 'dimension': return f'{value:g}px'
    if kind == 'duration': return f'{value:g}ms'
    if kind == 'bezier': return 'cubic-bezier(' + ', '.join(f'{v:g}' for v in value) + ')'
    return str(value)


def outputs(tree):
    tokens = flatten(tree)
    values = resolve(tokens)
    def rust(group, prefix='', depth=0):
        lines = []
        for key, token in group.items():
            if key.startswith('$'): continue
            path = f'{prefix}.{key}' if prefix else key
            indent = '    ' * depth
            if '$value' not in token:
                lines += [f'{indent}pub mod {key} {{', *rust(token, path, depth + 1), f'{indent}}}']
                continue
            kind, value = token['$type'], values[path]
            if kind == 'color': ty, literal = 'lucent_api::Color', f'lucent_api::Color::hex(0x{value[1:]})'
            elif kind == 'bezier': ty, literal = '[f32; 4]', '[' + ', '.join(str(float(v)) for v in value) + ']'
            elif kind == 'duration': ty, literal = 'f64', str(float(value) / 1000)
            else: ty, literal = 'f32', str(float(value))
            lines.append(f'{indent}pub const {key.upper()}: {ty} = {literal};')
        return lines
    rust_text = '// Generated by scripts/generate-design-tokens.py. Edit design/tokens.json.\n' + '\n'.join(rust(tree)) + '\n'
    css = ['/* Generated by scripts/generate-design-tokens.py. Edit design/tokens.json. */', ':root {']
    for name, token in tokens.items():
        raw = token['$value']
        value = f'var(--{raw[1:-1].replace(".", "-").replace("_", "-")})' if isinstance(raw, str) and raw.startswith('{') else css_value(token['$type'], values[name])
        css.append(f'  --{name.replace(".", "-").replace("_", "-").replace("_", "-")}: {value};')
    css.append('}')
    generated = {
        ROOT / 'lucent/crates/lucent-design/src/tokens.rs': rust_text,
        ROOT / 'site/src/styles/tokens.css': '\n'.join(css) + '\n',
        ROOT / 'configs/lucent/window-rules.lua': (
            '-- Generated from component.window tokens in design/tokens.json.\n'
            '-- Compositor default; explicit app rules and Omarchy gap toggles retain precedence.\n'
            'hl.config({\n'
            f'  general = {{ gaps_out = {values["component.window.gap_out"]:g}, '
            f'gaps_in = {values["component.window.gap_in"]:g} }},\n'
            f'  decoration = {{ rounding = {values["component.window.radius"]:g} }},\n'
            '})\n'
        ),
    }
    names = {'dark': 'Moonstone', 'light': 'Pearl', 'ocean': 'Ocean', 'forest': 'Forest', 'ember': 'Ember'}
    palettes = [{'id': mode, 'name': name, 'colors': {key: values[f'theme.{mode}.{key}'] for key in tree['theme'][mode]}} for mode, name in names.items()]
    generated[ROOT/'configs/lucent/palettes.json'] = json.dumps(palettes, indent=2) + '\n'
    for mode in ('dark', 'light'):
        role = lambda name: values[f'theme.{mode}.{name}']
        colors = {
            'mode': mode, 'accent': role('primary'), 'selection': role('surface_container'),
            'muted': role('surface_container'), 'background': role('surface'),
            'dark_background': role('surface_container'), 'darker_background': role('surface_container'),
            'lighter_background': role('surface_container'), 'foreground': role('on_surface'),
            'dark_foreground': role('on_surface'), 'light_foreground': role('on_surface'),
            'bright_foreground': role('on_surface'), 'red': role('error'),
            'yellow': role('warning'), 'orange': role('warning'), 'green': role('success'),
            'cyan': role('primary'), 'blue': role('info'), 'magenta': role('primary'),
            'brown': role('warning'),
        }
        for name in ('red', 'yellow', 'green', 'cyan', 'blue', 'magenta'):
            colors['bright_' + name] = colors[name]
        base = ROOT / 'configs/lucent/themes' / mode
        generated[base/'colors.toml'] = '# Generated from Lucent semantic tokens.\n' + ''.join(
            f'{name} = "{value}"\n' for name, value in colors.items())
        gtk = {'window_bg_color':'surface', 'window_fg_color':'on_surface',
               'view_bg_color':'surface_container', 'view_fg_color':'on_surface',
               'headerbar_bg_color':'surface', 'headerbar_fg_color':'on_surface',
               'card_bg_color':'surface_container', 'card_fg_color':'on_surface',
               'accent_bg_color':'primary', 'accent_fg_color':'on_primary', 'accent_color':'primary',
               'error_color':'error', 'warning_color':'warning', 'success_color':'success',
               'theme_bg_color':'surface', 'theme_fg_color':'on_surface',
               'theme_base_color':'surface_container', 'theme_text_color':'on_surface',
               'theme_selected_bg_color':'primary', 'theme_selected_fg_color':'on_primary'}
        generated[base/'gtk.css'] = '/* Generated from Lucent semantic tokens. */\n' + ''.join(
            f'@define-color {name} {role(value)};\n' for name,value in gtk.items())
        generated[base/'hyprlock.conf'] = (
            '# Emergency secure locker; generated from Lucent tokens.\n'
            'general {\n  ignore_empty_input = true\n}\n'
            'background {\n  monitor =\n  path = ~/.local/state/lucent/wallpaper\n'
            f'  color = rgb({role("surface")[1:]})\n  blur_passes = 0\n}}\n'
            'input-field {\n  monitor =\n'
            f'  size = {values["component.menu.min_width"]:g}, {values["component.input.height"]:g}\n'
            f'  rounding = {values["radius.control"]:g}\n'
            f'  inner_color = rgb({role("surface")[1:]})\n'
            f'  outer_color = rgb({role("primary")[1:]})\n'
            f'  font_color = rgb({role("on_surface")[1:]})\n'
            f'  fail_color = rgb({role("error")[1:]})\n'
            '  placeholder_text = Password\n  halign = center\n  valign = center\n}\n'
        )
    return generated


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if generated tokens are stale')
    args = parser.parse_args()
    tree = json.loads(SOURCE.read_text())
    stale = []
    for path, content in outputs(tree).items():
        if args.check:
            if not path.exists() or path.read_text() != content: stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        raise SystemExit('Run python3 scripts/generate-design-tokens.py; stale: ' + ', '.join(stale))
    print(f'{len(flatten(tree))} design tokens verified' if args.check else 'Generated Rust and CSS design tokens')


if __name__ == '__main__': main()
